// The `#[delegate]` macro from freenet-stdlib expands to
// `#[cfg(feature = "trace")]` internally; this crate doesn't declare a
// `trace` feature, so rustc flags the cfg as unexpected. Silence it here.
#![allow(unexpected_cfgs)]

use std::collections::HashMap;

use freenet_stdlib::prelude::*;
use p384::{FieldBytes, Scalar, SecretKey};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// Parameters: the same P-384 keying scheme as `identity-management`. The
/// secret key derives a `SecretsId` for the per-deployment stash. Drafts and
/// read-state for every alias on this device share that single stash; no
/// per-identity scoping at the delegate level (see `LocalState::for_alias`).
#[derive(Serialize, Deserialize)]
pub struct LocalStateParams {
    #[serde(serialize_with = "LocalStateParams::pk_serialize")]
    #[serde(deserialize_with = "LocalStateParams::pk_deserialize")]
    pub secret_key: SecretKey,
}

impl LocalStateParams {
    pub fn as_secret_id(&self) -> SecretsId {
        SecretsId::new(serde_json::to_vec(self).unwrap())
    }

    fn pk_deserialize<'de, D>(deser: D) -> Result<SecretKey, D::Error>
    where
        D: Deserializer<'de>,
    {
        let scalar = <Scalar as Deserialize>::deserialize(deser)?;
        Ok(SecretKey::from_bytes(&FieldBytes::from(scalar)).unwrap())
    }

    fn pk_serialize<S>(key: &SecretKey, ser: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let scalar: Scalar = key.as_scalar_primitive().into();
        scalar.serialize(ser)
    }
}

impl TryFrom<Parameters<'_>> for LocalStateParams {
    type Error = DelegateError;

    fn try_from(value: Parameters<'_>) -> Result<Self, Self::Error> {
        Self::try_from(value.as_ref())
    }
}

impl TryFrom<&[u8]> for LocalStateParams {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

impl TryFrom<LocalStateParams> for Parameters<'static> {
    type Error = DelegateError;

    fn try_from(value: LocalStateParams) -> Result<Self, Self::Error> {
        let ser = serde_json::to_vec(&value).map_err(|e| DelegateError::Deser(format!("{e}")))?;
        Ok(Parameters::from(ser))
    }
}

pub type Alias = String;
pub type DraftId = String; // UUID v4 string, generated by the UI.
pub type SentId = String; // UUID v4 string, generated by the UI.
pub type MessageId = u64;

/// Lifecycle of a sent message from the local Sent stash's perspective.
///
/// Under `use-node`, fresh sends start `Pending`; the api.rs response loop
/// flips them to `Delivered` when the recipient inbox contract returns an
/// `UpdateResponse`, or to `Failed` when `start_sending` errors out
/// asynchronously (AFT denied, encryption error, etc.). Under
/// `example-data,no-sync` there is no async ack signal so the UI sets
/// `Delivered` synchronously on send-button click. See issue #58.
///
/// Coverage gaps still tracked under #58: AFT delegate `Failure` responses
/// post-enqueue, inbox UPDATE timeouts, and AFT collision retry exhaustion
/// — these still leave a row stuck in `Pending`.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum DeliveryState {
    #[default]
    Pending,
    Delivered,
    Failed,
}

/// A snapshot of an inbox message that the user has explicitly archived.
/// 47c removes the row from the inbox contract on archive; the local copy
/// here keeps the message visible in the Archive folder. True unarchive
/// (re-PUT into the contract via an owner-signed delta) is tracked in #60.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct ArchivedMessage {
    pub from: String,
    pub title: String,
    pub content: String,
    /// Unix millis at the time the user clicked Archive.
    pub archived_at: i64,
}

/// A snapshot of an outgoing message stashed locally on Send. Mirrors what the
/// user typed plus enough metadata to render the Sent folder and to seed
/// Reply / Forward / Resend without round-tripping the contract.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct SentMessage {
    /// Recipient alias / address as typed in the compose To field.
    pub to: String,
    /// Short fingerprint of the recipient's verifying key at send time.
    /// Stored so the Sent UI can show trust info without a contact-book lookup.
    pub recipient_fingerprint: String,
    /// Full six-word fingerprint of the recipient. Empty for legacy rows
    /// written before this field existed; UI must fall back to the short
    /// form for hover/tooltip in that case.
    #[serde(default)]
    pub recipient_fingerprint_full: String,
    pub subject: String,
    pub body: String,
    /// Unix millis at send-button click time.
    pub sent_at: i64,
    #[serde(default)]
    pub delivery_state: DeliveryState,
}

/// A draft message saved by the compose form. Stored pre-encryption.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct Draft {
    pub to: String,
    pub subject: String,
    pub body: String,
    /// Unix millis. Used to order the Drafts list newest-first.
    pub updated_at: i64,
}

/// A message snapshot kept locally after the inbox contract has been told to
/// remove it. Lets the UI continue showing read mail across reloads even
/// though the contract no longer holds it. Encrypted fields are stored
/// post-decryption (the delegate stash is itself a per-device secret).
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct KeptMessage {
    pub from: String,
    pub title: String,
    pub content: String,
    /// Unix millis at the time `MarkRead` was issued; the contract message
    /// timestamp is not currently surfaced through the UI's `Message` type
    /// so we keep our own.
    pub kept_at: i64,
}

/// Per-identity AFT preferences. The required tier and the allow-known /
/// allow-anonymous flags govern which incoming messages this identity will
/// accept; `bounce_message` is shown to senders whose tier is below the
/// requirement (the chain itself just refuses; the bounce text is informational
/// and rendered locally on the sender side via the address book).
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone)]
pub struct IdentityAftPrefs {
    /// Minimum tier the identity will accept. Stored as the canonical
    /// freenet-aft-interface tier name. The full set is enumerated by
    /// `freenet_aft_interface::Tier` (`Min1`, `Min5`, `Min10`, `Min30`,
    /// `Hour1`, `Hour3`, `Hour6`, `Hour12`, `Day1`, `Day7`, `Day15`,
    /// `Day30`, `Day90`, `Day180`, `Day365`).
    pub required_tier: String,
    /// Accept messages from contacts in the address book regardless of tier.
    pub allow_known: bool,
    /// Accept messages from senders not in the address book.
    pub allow_anon: bool,
    /// Optional bounce message shown to senders below the required tier.
    pub bounce_message: String,
}

impl Default for IdentityAftPrefs {
    fn default() -> Self {
        Self {
            required_tier: "Day1".to_string(),
            allow_known: true,
            allow_anon: false,
            bounce_message: String::new(),
        }
    }
}

/// Per-identity privacy preferences. Govern client-side composition and
/// display behavior; nothing here is enforced by the chain.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone)]
pub struct IdentityPrivacyPrefs {
    /// Verify the recipient's signing key against the address book before
    /// sending. Refuse to compose if the verifying key has changed since
    /// import.
    pub verify_on_send: bool,
    /// Hide unsigned / unverifiable inbound messages from the inbox list.
    pub hide_unsigned: bool,
    /// Pad outgoing ciphertexts to a length-class boundary to reduce
    /// linkability of message size.
    pub pad_length: bool,
    /// Send a read receipt automatically when an inbox row is opened.
    pub read_receipts: bool,
}

impl Default for IdentityPrivacyPrefs {
    fn default() -> Self {
        Self {
            verify_on_send: true,
            hide_unsigned: false,
            pad_length: true,
            read_receipts: false,
        }
    }
}

/// Per-identity settings: the parts of Settings that are scoped to a single
/// alias rather than to the whole device.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone)]
pub struct IdentitySettings {
    /// Display name shown to recipients alongside the alias. Empty means
    /// "use the alias verbatim".
    #[serde(default)]
    pub display_name: String,
    /// Signature appended to outgoing messages. Empty means no signature.
    #[serde(default)]
    pub signature: String,
    /// Whether to append the signature automatically. If false, the user
    /// has to opt in per-message in the compose form.
    #[serde(default = "default_true")]
    pub auto_sign: bool,
    #[serde(default)]
    pub aft: IdentityAftPrefs,
    #[serde(default)]
    pub privacy: IdentityPrivacyPrefs,
    /// Unix millis of the most recent successful key-bundle export. `None`
    /// means the identity has never been backed up on this device — the
    /// Settings UI surfaces an amber banner in that case.
    #[serde(default)]
    pub last_backup_at: Option<i64>,
}

impl Default for IdentitySettings {
    fn default() -> Self {
        Self {
            display_name: String::new(),
            signature: String::new(),
            auto_sign: true,
            aft: IdentityAftPrefs::default(),
            privacy: IdentityPrivacyPrefs::default(),
            last_backup_at: None,
        }
    }
}

fn default_true() -> bool {
    true
}

/// Per-alias local state: drafts, the set of read message ids, a local
/// snapshot of those messages so the UI can keep displaying them after the
/// inbox contract has evicted them, and outgoing-message snapshots for the
/// Sent folder.
#[derive(Deserialize, Serialize, Debug, Clone, Default)]
pub struct AliasState {
    #[serde(default)]
    pub drafts: HashMap<DraftId, Draft>,
    #[serde(default)]
    pub read: Vec<MessageId>,
    #[serde(default)]
    pub kept: HashMap<String, KeptMessage>,
    #[serde(default)]
    pub sent: HashMap<SentId, SentMessage>,
    /// Inbox messages explicitly archived by the user. Keyed by stringified
    /// `MessageId` (matching the kept map's convention).
    #[serde(default)]
    pub archived: HashMap<String, ArchivedMessage>,
    /// Inbox message ids the user has explicitly deleted. Used to hide rows
    /// in the Inbox view even when the contract eviction has not yet taken
    /// effect (or, in offline / mock mode, never will). The list is bounded
    /// by the number of messages the user has touched.
    #[serde(default)]
    pub deleted: Vec<MessageId>,
    /// Per-identity Settings buckets (Account, Privacy, AFT). `#[serde(default)]`
    /// so older serialized state without this field still loads.
    #[serde(default)]
    pub settings: IdentitySettings,
}

/// UI theme preference. `System` follows the OS dark/light setting.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum Theme {
    #[default]
    System,
    Light,
    Dark,
}

/// UI density preference. Controls row spacing in the inbox list.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum Density {
    #[default]
    Comfortable,
    Compact,
}

/// Appearance settings (global, not per-identity).
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone)]
pub struct AppearanceSettings {
    #[serde(default)]
    pub theme: Theme,
    #[serde(default)]
    pub density: Density,
    /// Render subject lines in the serif display face.
    #[serde(default = "default_true")]
    pub serif_subjects: bool,
}

impl Default for AppearanceSettings {
    fn default() -> Self {
        Self {
            theme: Theme::default(),
            density: Density::default(),
            serif_subjects: true,
        }
    }
}

/// Inbox-folder settings (global). Govern UI grouping / quarantine behavior.
///
/// Both fields default to `false`. `quarantine_unknown=true` would silently
/// hide every unsigned/legacy inbound message until the user verifies the
/// sender, which is hostile for first-run UX; users who want strict
/// quarantine flip the toggle in Settings > Inbox.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct InboxSettings {
    /// Show drafts inline in the inbox list rather than only in the
    /// Drafts folder.
    pub drafts_in_inbox: bool,
    /// Move messages from senders not in the address book into a
    /// quarantine folder instead of the inbox.
    pub quarantine_unknown: bool,
}

/// Advanced / node-connection settings.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct AdvancedSettings {
    /// Use a non-default Freenet node WebSocket endpoint. When false the
    /// UI talks to the bundled host page's relay.
    #[serde(default)]
    pub custom_relay: bool,
    /// Optional override URL for the Freenet node WebSocket. Used only
    /// when `custom_relay` is true.
    #[serde(default)]
    pub custom_relay_url: String,
}

/// Global (device-scoped) settings buckets.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct GlobalSettings {
    #[serde(default)]
    pub appearance: AppearanceSettings,
    #[serde(default)]
    pub inbox: InboxSettings,
    #[serde(default)]
    pub advanced: AdvancedSettings,
}

#[derive(Deserialize, Serialize, Debug, Default)]
pub struct LocalState {
    aliases: HashMap<Alias, AliasState>,
    /// Device-scoped Settings (Appearance, Inbox/Folders, Advanced).
    /// `#[serde(default)]` so older serialized state without this field
    /// still loads.
    #[serde(default)]
    settings: GlobalSettings,
}

impl LocalState {
    pub fn for_alias(&self, alias: &str) -> Option<&AliasState> {
        self.aliases.get(alias)
    }

    /// Mutable access to the per-alias map. Exposed so the UI can apply
    /// optimistic updates to its in-memory snapshot without round-tripping
    /// through the delegate. The delegate itself never goes through this
    /// path — it owns the canonical state.
    pub fn aliases_mut(&mut self) -> &mut HashMap<Alias, AliasState> {
        &mut self.aliases
    }

    pub fn drafts_of(&self, alias: &str) -> impl Iterator<Item = (&DraftId, &Draft)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.drafts.iter())
    }

    pub fn is_read(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.read.contains(&id))
    }

    pub fn sent_of(&self, alias: &str) -> impl Iterator<Item = (&SentId, &SentMessage)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.sent.iter())
    }

    pub fn archived_of(&self, alias: &str) -> impl Iterator<Item = (&String, &ArchivedMessage)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.archived.iter())
    }

    /// Whether `id` was archived by `alias`. Used by the Inbox merge to hide
    /// rows the user has moved to the Archive folder.
    pub fn is_archived(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.archived.contains_key(&id.to_string()))
    }

    pub fn is_deleted(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.deleted.contains(&id))
    }

    /// Per-identity settings for `alias`. Returns `IdentitySettings::default()`
    /// for unknown aliases — callers don't need to special-case absence.
    pub fn identity_settings(&self, alias: &str) -> IdentitySettings {
        self.aliases
            .get(alias)
            .map(|s| s.settings.clone())
            .unwrap_or_default()
    }

    /// Device-scoped settings.
    pub fn global_settings(&self) -> &GlobalSettings {
        &self.settings
    }

    /// Mutable global settings. Same caveat as `aliases_mut`: only the UI
    /// optimistic-update path goes through this; the delegate owns the
    /// canonical state.
    pub fn global_settings_mut(&mut self) -> &mut GlobalSettings {
        &mut self.settings
    }
}

impl TryFrom<&[u8]> for LocalState {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub enum LocalStateMsg {
    /// Idempotent: creates an empty stash if absent, else no-op.
    Init,
    SaveDraft {
        alias: Alias,
        id: DraftId,
        draft: Draft,
    },
    DeleteDraft {
        alias: Alias,
        id: DraftId,
    },
    /// Mark a message id as read AND stash a local snapshot so the UI keeps
    /// displaying it after the inbox contract evicts the row.
    MarkRead {
        alias: Alias,
        msg_id: MessageId,
        kept: KeptMessage,
    },
    /// Stash a snapshot of an outgoing message for the Sent folder. Issued
    /// from the compose-Send handler; the UI assigns the `id` (UUID v4).
    SaveSent {
        alias: Alias,
        id: SentId,
        sent: SentMessage,
    },
    DeleteSent {
        alias: Alias,
        id: SentId,
    },
    /// Flip the `delivery_state` of a previously-saved sent message.
    /// Issued from the api response handler when an inbox UPDATE is acked
    /// (→ `Delivered`) or when AFT allocation / UPDATE error fires
    /// (→ `Failed`). No-op if the id is not in the alias's sent map —
    /// avoids races where the user manually deletes a sent row before
    /// the ack arrives.
    SetSentDeliveryState {
        alias: Alias,
        id: SentId,
        state: DeliveryState,
    },
    /// Stash an inbox message in the local archive. Issued from OpenMessage's
    /// Archive button; the UI also fires a `remove_messages` against the
    /// inbox contract. True unarchive (re-PUT into the contract) is tracked
    /// in #60.
    ArchiveMessage {
        alias: Alias,
        msg_id: MessageId,
        archived: ArchivedMessage,
    },
    /// Drop the local archive entry for `msg_id`. Does NOT re-insert into
    /// the contract — that path is gated on #60.
    UnarchiveMessage {
        alias: Alias,
        msg_id: MessageId,
    },
    /// Hard delete an inbox message: clear any local copies (kept + archived)
    /// for that id. The caller is also expected to have issued
    /// `remove_messages` against the inbox contract.
    DeleteMessage {
        alias: Alias,
        msg_id: MessageId,
    },
    /// Replace the per-identity Settings bucket for `alias`. The whole
    /// bucket is sent rather than diffed: the bucket is small (a few
    /// flags + two strings) and last-write-wins is the right semantic for
    /// UI-driven preference edits.
    SetIdentitySettings {
        alias: Alias,
        settings: IdentitySettings,
    },
    /// Replace the device-scoped Settings (Appearance / Inbox / Advanced).
    /// Same last-write-wins rationale as `SetIdentitySettings`.
    SetGlobalSettings {
        settings: GlobalSettings,
    },
    /// Returns the entire `LocalState` JSON via an `ApplicationMessage`
    /// response. UI filters per active alias.
    GetAll,
}

impl TryFrom<&[u8]> for LocalStateMsg {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

impl TryFrom<&LocalStateMsg> for Vec<u8> {
    type Error = DelegateError;

    fn try_from(value: &LocalStateMsg) -> Result<Self, Self::Error> {
        serde_json::to_vec(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

#[delegate]
impl DelegateInterface for LocalState {
    fn process(
        ctx: &mut DelegateCtx,
        params: Parameters<'static>,
        _origin: Option<MessageOrigin>,
        message: InboundDelegateMsg,
    ) -> Result<Vec<OutboundDelegateMsg>, DelegateError> {
        let params = LocalStateParams::try_from(params)?;
        let secret_key =
            serde_json::to_vec(&params).map_err(|e| DelegateError::Deser(format!("{e}")))?;
        match message {
            InboundDelegateMsg::ApplicationMessage(ApplicationMessage {
                payload,
                processed: false,
                ..
            }) => {
                let msg = LocalStateMsg::try_from(&*payload)?;
                match msg {
                    LocalStateMsg::Init => {
                        if ctx.get_secret(&secret_key).is_some() {
                            return Ok(vec![]);
                        }
                        let default_value = serde_json::to_vec(&LocalState::default())
                            .map_err(|e| DelegateError::Deser(format!("{e}")))?;
                        ctx.set_secret(&secret_key, &default_value);
                        Ok(vec![])
                    }
                    LocalStateMsg::SaveDraft { alias, id, draft } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state
                            .aliases
                            .entry(alias)
                            .or_default()
                            .drafts
                            .insert(id, draft);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteDraft { alias, id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.drafts.remove(&id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::MarkRead {
                        alias,
                        msg_id,
                        kept,
                    } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        if !s.read.contains(&msg_id) {
                            s.read.push(msg_id);
                        }
                        s.kept.insert(msg_id.to_string(), kept);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::ArchiveMessage {
                        alias,
                        msg_id,
                        archived,
                    } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        // Archiving is also "read" by definition — the user
                        // explicitly acted on it. Drop any kept copy so the
                        // message isn't surfaced twice (Inbox via kept fallback
                        // AND Archive folder).
                        s.kept.remove(&msg_id.to_string());
                        if !s.read.contains(&msg_id) {
                            s.read.push(msg_id);
                        }
                        s.archived.insert(msg_id.to_string(), archived);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::UnarchiveMessage { alias, msg_id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.archived.remove(&msg_id.to_string());
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteMessage { alias, msg_id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        s.kept.remove(&msg_id.to_string());
                        s.archived.remove(&msg_id.to_string());
                        s.read.retain(|id| *id != msg_id);
                        if !s.deleted.contains(&msg_id) {
                            s.deleted.push(msg_id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::SaveSent { alias, id, sent } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state
                            .aliases
                            .entry(alias)
                            .or_default()
                            .sent
                            .insert(id, sent);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteSent { alias, id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.sent.remove(&id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::SetSentDeliveryState {
                        alias,
                        id,
                        state: ds,
                    } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias)
                            && let Some(sent) = s.sent.get_mut(&id)
                        {
                            sent.delivery_state = ds;
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::SetIdentitySettings { alias, settings } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state.aliases.entry(alias).or_default().settings = settings;
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::SetGlobalSettings { settings } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state.settings = settings;
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::GetAll => {
                        let value = ctx
                            .get_secret(&secret_key)
                            .unwrap_or_else(|| serde_json::to_vec(&LocalState::default()).unwrap());
                        Ok(vec![OutboundDelegateMsg::ApplicationMessage(
                            ApplicationMessage::new(value),
                        )])
                    }
                }
            }
            _ => Err(DelegateError::Other("unexpected message type".into())),
        }
    }
}

fn load_or_default(ctx: &mut DelegateCtx, key: &[u8]) -> Result<LocalState, DelegateError> {
    match ctx.get_secret(key) {
        Some(bytes) => LocalState::try_from(bytes.as_slice()),
        None => Ok(LocalState::default()),
    }
}

fn store(ctx: &mut DelegateCtx, key: &[u8], state: &LocalState) -> Result<(), DelegateError> {
    let bytes = serde_json::to_vec(state).map_err(|e| DelegateError::Deser(format!("{e}")))?;
    ctx.set_secret(key, &bytes);
    Ok(())
}

#[cfg(test)]
mod boundary_tests {
    //! Regression tests for the deserialization boundaries.
    //!
    //! `LocalState` and `LocalStateMsg` are reachable from network input via
    //! `DelegateInterface::process`. Every `try_from(&[u8])` must return
    //! `Err(DelegateError::Deser)` rather than panic on malformed input.

    use super::*;

    #[test]
    fn malformed_local_state_bytes_returns_err() {
        let garbage = [0xffu8; 64];
        let result = LocalState::try_from(&garbage[..]);
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn truncated_local_state_json_returns_err() {
        let truncated = br#"{"aliases":{"alice":"#;
        let result = LocalState::try_from(&truncated[..]);
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn malformed_msg_bytes_returns_err() {
        let garbage = [0xffu8; 64];
        let result = LocalStateMsg::try_from(&garbage[..]).map(|_| ());
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn empty_msg_bytes_returns_err() {
        let result = LocalStateMsg::try_from(&[][..]).map(|_| ());
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    /// `AliasState` missing the read list (older serialized state) deserializes
    /// with an empty default. Backwards-compat for any state written before the
    /// read-tracking field landed.
    #[test]
    fn alias_state_missing_read_defaults_empty() {
        let json = br#"{"drafts":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.read.is_empty());
    }

    #[test]
    fn alias_state_missing_drafts_defaults_empty() {
        let json = br#"{"read":[1,2]}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.drafts.is_empty());
        assert_eq!(s.read, vec![1, 2]);
    }

    #[test]
    fn round_trip_mixed_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.drafts.insert(
            "00000000-0000-4000-8000-000000000000".into(),
            Draft {
                to: "bob".into(),
                subject: "hi".into(),
                body: "yo".into(),
                updated_at: 42,
            },
        );
        alias.read.push(7);
        alias.kept.insert(
            "7".into(),
            KeptMessage {
                from: "bob".into(),
                title: "hi".into(),
                content: "yo".into(),
                kept_at: 42,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        assert!(back.is_read("alice", 7));
        assert_eq!(back.drafts_of("alice").count(), 1);
        assert_eq!(back.aliases["alice"].kept["7"].content.as_str(), "yo");
    }

    #[test]
    fn alias_state_missing_kept_defaults_empty() {
        let json = br#"{"drafts":{},"read":[1]}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.kept.is_empty());
    }

    /// `AliasState` written before the Sent feature deserialises with an empty
    /// `sent` map. Pre-#47b state must keep loading.
    #[test]
    fn alias_state_missing_sent_defaults_empty() {
        let json = br#"{"drafts":{},"read":[1],"kept":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.sent.is_empty());
    }

    /// `SentMessage` without an explicit `delivery_state` deserialises as
    /// `Pending` (the default).
    #[test]
    fn sent_message_missing_delivery_state_defaults_pending() {
        let json = br#"{"to":"bob","recipient_fingerprint":"abcd","subject":"hi","body":"yo","sent_at":1}"#;
        let s: SentMessage = serde_json::from_slice(json).expect("should deserialise");
        assert_eq!(s.delivery_state, DeliveryState::Pending);
    }

    /// `AliasState` written before the Archive feature deserialises with an
    /// empty `archived` map. Pre-#47c state must keep loading.
    #[test]
    fn alias_state_missing_archived_defaults_empty() {
        let json = br#"{"drafts":{},"read":[],"kept":{},"sent":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.archived.is_empty());
    }

    #[test]
    fn round_trip_archived_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.archived.insert(
            "9".into(),
            ArchivedMessage {
                from: "bob".into(),
                title: "old".into(),
                content: "stash".into(),
                archived_at: 99,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        assert!(back.is_archived("alice", 9));
        let archived: Vec<_> = back.archived_of("alice").collect();
        assert_eq!(archived.len(), 1);
        assert_eq!(archived[0].1.content.as_str(), "stash");
    }

    /// `IdentitySettings` written before the `last_backup_at` field landed
    /// loads with `last_backup_at = None`. Verifies the new field is
    /// additive, not a breaking change.
    #[test]
    fn identity_settings_missing_last_backup_defaults_none() {
        let json = br#"{"display_name":"","signature":"","auto_sign":true,"aft":{"required_tier":"Day1","allow_known":true,"allow_anon":false,"bounce_message":""},"privacy":{"verify_on_send":true,"hide_unsigned":false,"pad_length":true,"read_receipts":false}}"#;
        let s: IdentitySettings = serde_json::from_slice(json).expect("should deserialise");
        assert_eq!(s.last_backup_at, None);
    }

    /// `AliasState` written before the Settings feature deserialises with
    /// default `settings` (Day1, allow-known on, signature off, etc.).
    /// Pre-Settings state must keep loading.
    #[test]
    fn alias_state_missing_settings_defaults_loaded() {
        let json = br#"{"drafts":{},"read":[],"kept":{},"sent":{},"archived":{},"deleted":[]}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert_eq!(s.settings.aft.required_tier, "Day1");
        assert!(s.settings.aft.allow_known);
        assert!(!s.settings.aft.allow_anon);
        assert!(s.settings.privacy.verify_on_send);
        assert!(s.settings.auto_sign);
    }

    /// `LocalState` written before the global-Settings feature deserialises
    /// with default appearance / inbox / advanced.
    #[test]
    fn local_state_missing_settings_defaults_loaded() {
        let json = br#"{"aliases":{}}"#;
        let s: LocalState = serde_json::from_slice(json).expect("should deserialise");
        assert!(matches!(s.settings.appearance.theme, Theme::System));
        assert!(s.settings.appearance.serif_subjects);
        assert!(!s.settings.inbox.quarantine_unknown);
        assert!(!s.settings.advanced.custom_relay);
    }

    #[test]
    fn round_trip_identity_settings() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.settings = IdentitySettings {
            display_name: "Alice in Wonderland".into(),
            signature: "— A".into(),
            auto_sign: false,
            aft: IdentityAftPrefs {
                required_tier: "Mid2".into(),
                allow_known: true,
                allow_anon: true,
                bounce_message: "rate-limited".into(),
            },
            privacy: IdentityPrivacyPrefs {
                verify_on_send: false,
                hide_unsigned: true,
                pad_length: false,
                read_receipts: true,
            },
            last_backup_at: Some(1_700_000_000_000),
        };
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        let s = back.identity_settings("alice");
        assert_eq!(s.display_name, "Alice in Wonderland");
        assert!(!s.auto_sign);
        assert_eq!(s.aft.required_tier, "Mid2");
        assert!(s.aft.allow_anon);
        assert!(s.privacy.hide_unsigned);
        assert_eq!(s.last_backup_at, Some(1_700_000_000_000));
    }

    #[test]
    fn round_trip_global_settings() {
        let mut state = LocalState::default();
        *state.global_settings_mut() = GlobalSettings {
            appearance: AppearanceSettings {
                theme: Theme::Dark,
                density: Density::Compact,
                serif_subjects: false,
            },
            inbox: InboxSettings {
                drafts_in_inbox: true,
                quarantine_unknown: false,
            },
            advanced: AdvancedSettings {
                custom_relay: true,
                custom_relay_url: "ws://localhost:7510".into(),
            },
        };
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        let g = back.global_settings();
        assert!(matches!(g.appearance.theme, Theme::Dark));
        assert!(matches!(g.appearance.density, Density::Compact));
        assert!(!g.appearance.serif_subjects);
        assert!(g.inbox.drafts_in_inbox);
        assert!(g.advanced.custom_relay);
        assert_eq!(g.advanced.custom_relay_url, "ws://localhost:7510");
    }

    #[test]
    fn round_trip_sent_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.sent.insert(
            "00000000-0000-4000-8000-000000000001".into(),
            SentMessage {
                to: "bob".into(),
                recipient_fingerprint: "AB12".into(),
                recipient_fingerprint_full: "AB12-CD34-EF56".into(),
                subject: "hi".into(),
                body: "yo".into(),
                sent_at: 42,
                delivery_state: DeliveryState::Delivered,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        let mut iter = back.sent_of("alice");
        let (_id, sent) = iter.next().expect("one sent");
        assert!(iter.next().is_none());
        assert_eq!(sent.to, "bob");
        assert_eq!(sent.delivery_state, DeliveryState::Delivered);
    }
}
