// The `#[delegate]` macro from freenet-stdlib expands to
// `#[cfg(feature = "trace")]` internally; this crate doesn't declare a
// `trace` feature, so rustc flags the cfg as unexpected. Silence it here.
#![allow(unexpected_cfgs)]

use std::collections::HashMap;

use freenet_stdlib::prelude::*;
use p384::{FieldBytes, Scalar, SecretKey};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// Parameters: the same P-384 keying scheme as `identity-management`. The
/// secret key derives a `SecretsId` for the per-deployment stash. Drafts and
/// read-state for every alias on this device share that single stash; no
/// per-identity scoping at the delegate level (see `LocalState::for_alias`).
#[derive(Serialize, Deserialize)]
pub struct LocalStateParams {
    #[serde(serialize_with = "LocalStateParams::pk_serialize")]
    #[serde(deserialize_with = "LocalStateParams::pk_deserialize")]
    pub secret_key: SecretKey,
}

impl LocalStateParams {
    pub fn as_secret_id(&self) -> SecretsId {
        SecretsId::new(serde_json::to_vec(self).unwrap())
    }

    fn pk_deserialize<'de, D>(deser: D) -> Result<SecretKey, D::Error>
    where
        D: Deserializer<'de>,
    {
        let scalar = <Scalar as Deserialize>::deserialize(deser)?;
        Ok(SecretKey::from_bytes(&FieldBytes::from(scalar)).unwrap())
    }

    fn pk_serialize<S>(key: &SecretKey, ser: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let scalar: Scalar = key.as_scalar_primitive().into();
        scalar.serialize(ser)
    }
}

impl TryFrom<Parameters<'_>> for LocalStateParams {
    type Error = DelegateError;

    fn try_from(value: Parameters<'_>) -> Result<Self, Self::Error> {
        Self::try_from(value.as_ref())
    }
}

impl TryFrom<&[u8]> for LocalStateParams {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

impl TryFrom<LocalStateParams> for Parameters<'static> {
    type Error = DelegateError;

    fn try_from(value: LocalStateParams) -> Result<Self, Self::Error> {
        let ser = serde_json::to_vec(&value).map_err(|e| DelegateError::Deser(format!("{e}")))?;
        Ok(Parameters::from(ser))
    }
}

pub type Alias = String;
pub type DraftId = String; // UUID v4 string, generated by the UI.
pub type SentId = String; // UUID v4 string, generated by the UI.
pub type MessageId = u64;

/// Optimistic best-guess of whether the inbox contract UPDATE that carried this
/// message landed. 47b sets `Delivered` on send-button click; the
/// `Pending → Delivered/Failed` state machine driven by a real ack signal
/// from the contract is tracked in issue #58.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum DeliveryState {
    #[default]
    Pending,
    Delivered,
    Failed,
}

/// A snapshot of an inbox message that the user has explicitly archived.
/// 47c removes the row from the inbox contract on archive; the local copy
/// here keeps the message visible in the Archive folder. True unarchive
/// (re-PUT into the contract via an owner-signed delta) is tracked in #60.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct ArchivedMessage {
    pub from: String,
    pub title: String,
    pub content: String,
    /// Unix millis at the time the user clicked Archive.
    pub archived_at: i64,
}

/// A snapshot of an outgoing message stashed locally on Send. Mirrors what the
/// user typed plus enough metadata to render the Sent folder and to seed
/// Reply / Forward / Resend without round-tripping the contract.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct SentMessage {
    /// Recipient alias / address as typed in the compose To field.
    pub to: String,
    /// Short fingerprint of the recipient's verifying key at send time.
    /// Stored so the Sent UI can show trust info without a contact-book lookup.
    pub recipient_fingerprint: String,
    pub subject: String,
    pub body: String,
    /// Unix millis at send-button click time.
    pub sent_at: i64,
    #[serde(default)]
    pub delivery_state: DeliveryState,
}

/// A draft message saved by the compose form. Stored pre-encryption.
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct Draft {
    pub to: String,
    pub subject: String,
    pub body: String,
    /// Unix millis. Used to order the Drafts list newest-first.
    pub updated_at: i64,
}

/// A message snapshot kept locally after the inbox contract has been told to
/// remove it. Lets the UI continue showing read mail across reloads even
/// though the contract no longer holds it. Encrypted fields are stored
/// post-decryption (the delegate stash is itself a per-device secret).
#[derive(Deserialize, Serialize, PartialEq, Eq, Debug, Clone, Default)]
pub struct KeptMessage {
    pub from: String,
    pub title: String,
    pub content: String,
    /// Unix millis at the time `MarkRead` was issued; the contract message
    /// timestamp is not currently surfaced through the UI's `Message` type
    /// so we keep our own.
    pub kept_at: i64,
}

/// Per-alias local state: drafts, the set of read message ids, a local
/// snapshot of those messages so the UI can keep displaying them after the
/// inbox contract has evicted them, and outgoing-message snapshots for the
/// Sent folder.
#[derive(Deserialize, Serialize, Debug, Clone, Default)]
pub struct AliasState {
    #[serde(default)]
    pub drafts: HashMap<DraftId, Draft>,
    #[serde(default)]
    pub read: Vec<MessageId>,
    #[serde(default)]
    pub kept: HashMap<String, KeptMessage>,
    #[serde(default)]
    pub sent: HashMap<SentId, SentMessage>,
    /// Inbox messages explicitly archived by the user. Keyed by stringified
    /// `MessageId` (matching the kept map's convention).
    #[serde(default)]
    pub archived: HashMap<String, ArchivedMessage>,
    /// Inbox message ids the user has explicitly deleted. Used to hide rows
    /// in the Inbox view even when the contract eviction has not yet taken
    /// effect (or, in offline / mock mode, never will). The list is bounded
    /// by the number of messages the user has touched.
    #[serde(default)]
    pub deleted: Vec<MessageId>,
}

#[derive(Deserialize, Serialize, Debug, Default)]
pub struct LocalState {
    aliases: HashMap<Alias, AliasState>,
}

impl LocalState {
    pub fn for_alias(&self, alias: &str) -> Option<&AliasState> {
        self.aliases.get(alias)
    }

    /// Mutable access to the per-alias map. Exposed so the UI can apply
    /// optimistic updates to its in-memory snapshot without round-tripping
    /// through the delegate. The delegate itself never goes through this
    /// path — it owns the canonical state.
    pub fn aliases_mut(&mut self) -> &mut HashMap<Alias, AliasState> {
        &mut self.aliases
    }

    pub fn drafts_of(&self, alias: &str) -> impl Iterator<Item = (&DraftId, &Draft)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.drafts.iter())
    }

    pub fn is_read(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.read.contains(&id))
    }

    pub fn sent_of(&self, alias: &str) -> impl Iterator<Item = (&SentId, &SentMessage)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.sent.iter())
    }

    pub fn archived_of(&self, alias: &str) -> impl Iterator<Item = (&String, &ArchivedMessage)> {
        self.aliases
            .get(alias)
            .into_iter()
            .flat_map(|s| s.archived.iter())
    }

    /// Whether `id` was archived by `alias`. Used by the Inbox merge to hide
    /// rows the user has moved to the Archive folder.
    pub fn is_archived(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.archived.contains_key(&id.to_string()))
    }

    pub fn is_deleted(&self, alias: &str, id: MessageId) -> bool {
        self.aliases
            .get(alias)
            .is_some_and(|s| s.deleted.contains(&id))
    }
}

impl TryFrom<&[u8]> for LocalState {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub enum LocalStateMsg {
    /// Idempotent: creates an empty stash if absent, else no-op.
    Init,
    SaveDraft {
        alias: Alias,
        id: DraftId,
        draft: Draft,
    },
    DeleteDraft {
        alias: Alias,
        id: DraftId,
    },
    /// Mark a message id as read AND stash a local snapshot so the UI keeps
    /// displaying it after the inbox contract evicts the row.
    MarkRead {
        alias: Alias,
        msg_id: MessageId,
        kept: KeptMessage,
    },
    /// Stash a snapshot of an outgoing message for the Sent folder. Issued
    /// from the compose-Send handler; the UI assigns the `id` (UUID v4).
    SaveSent {
        alias: Alias,
        id: SentId,
        sent: SentMessage,
    },
    DeleteSent {
        alias: Alias,
        id: SentId,
    },
    /// Stash an inbox message in the local archive. Issued from OpenMessage's
    /// Archive button; the UI also fires a `remove_messages` against the
    /// inbox contract. True unarchive (re-PUT into the contract) is tracked
    /// in #60.
    ArchiveMessage {
        alias: Alias,
        msg_id: MessageId,
        archived: ArchivedMessage,
    },
    /// Drop the local archive entry for `msg_id`. Does NOT re-insert into
    /// the contract — that path is gated on #60.
    UnarchiveMessage {
        alias: Alias,
        msg_id: MessageId,
    },
    /// Hard delete an inbox message: clear any local copies (kept + archived)
    /// for that id. The caller is also expected to have issued
    /// `remove_messages` against the inbox contract.
    DeleteMessage {
        alias: Alias,
        msg_id: MessageId,
    },
    /// Returns the entire `LocalState` JSON via an `ApplicationMessage`
    /// response. UI filters per active alias.
    GetAll,
}

impl TryFrom<&[u8]> for LocalStateMsg {
    type Error = DelegateError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        serde_json::from_slice(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

impl TryFrom<&LocalStateMsg> for Vec<u8> {
    type Error = DelegateError;

    fn try_from(value: &LocalStateMsg) -> Result<Self, Self::Error> {
        serde_json::to_vec(value).map_err(|e| DelegateError::Deser(format!("{e}")))
    }
}

#[delegate]
impl DelegateInterface for LocalState {
    fn process(
        ctx: &mut DelegateCtx,
        params: Parameters<'static>,
        _origin: Option<MessageOrigin>,
        message: InboundDelegateMsg,
    ) -> Result<Vec<OutboundDelegateMsg>, DelegateError> {
        let params = LocalStateParams::try_from(params)?;
        let secret_key =
            serde_json::to_vec(&params).map_err(|e| DelegateError::Deser(format!("{e}")))?;
        match message {
            InboundDelegateMsg::ApplicationMessage(ApplicationMessage {
                payload,
                processed: false,
                ..
            }) => {
                let msg = LocalStateMsg::try_from(&*payload)?;
                match msg {
                    LocalStateMsg::Init => {
                        if ctx.get_secret(&secret_key).is_some() {
                            return Ok(vec![]);
                        }
                        let default_value = serde_json::to_vec(&LocalState::default())
                            .map_err(|e| DelegateError::Deser(format!("{e}")))?;
                        ctx.set_secret(&secret_key, &default_value);
                        Ok(vec![])
                    }
                    LocalStateMsg::SaveDraft { alias, id, draft } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state
                            .aliases
                            .entry(alias)
                            .or_default()
                            .drafts
                            .insert(id, draft);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteDraft { alias, id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.drafts.remove(&id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::MarkRead {
                        alias,
                        msg_id,
                        kept,
                    } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        if !s.read.contains(&msg_id) {
                            s.read.push(msg_id);
                        }
                        s.kept.insert(msg_id.to_string(), kept);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::ArchiveMessage {
                        alias,
                        msg_id,
                        archived,
                    } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        // Archiving is also "read" by definition — the user
                        // explicitly acted on it. Drop any kept copy so the
                        // message isn't surfaced twice (Inbox via kept fallback
                        // AND Archive folder).
                        s.kept.remove(&msg_id.to_string());
                        if !s.read.contains(&msg_id) {
                            s.read.push(msg_id);
                        }
                        s.archived.insert(msg_id.to_string(), archived);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::UnarchiveMessage { alias, msg_id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.archived.remove(&msg_id.to_string());
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteMessage { alias, msg_id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        let s = state.aliases.entry(alias).or_default();
                        s.kept.remove(&msg_id.to_string());
                        s.archived.remove(&msg_id.to_string());
                        s.read.retain(|id| *id != msg_id);
                        if !s.deleted.contains(&msg_id) {
                            s.deleted.push(msg_id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::SaveSent { alias, id, sent } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        state
                            .aliases
                            .entry(alias)
                            .or_default()
                            .sent
                            .insert(id, sent);
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::DeleteSent { alias, id } => {
                        let mut state = load_or_default(ctx, &secret_key)?;
                        if let Some(s) = state.aliases.get_mut(&alias) {
                            s.sent.remove(&id);
                        }
                        store(ctx, &secret_key, &state)?;
                        Ok(vec![])
                    }
                    LocalStateMsg::GetAll => {
                        let value = ctx
                            .get_secret(&secret_key)
                            .unwrap_or_else(|| serde_json::to_vec(&LocalState::default()).unwrap());
                        Ok(vec![OutboundDelegateMsg::ApplicationMessage(
                            ApplicationMessage::new(value),
                        )])
                    }
                }
            }
            _ => Err(DelegateError::Other("unexpected message type".into())),
        }
    }
}

fn load_or_default(ctx: &mut DelegateCtx, key: &[u8]) -> Result<LocalState, DelegateError> {
    match ctx.get_secret(key) {
        Some(bytes) => LocalState::try_from(bytes.as_slice()),
        None => Ok(LocalState::default()),
    }
}

fn store(ctx: &mut DelegateCtx, key: &[u8], state: &LocalState) -> Result<(), DelegateError> {
    let bytes = serde_json::to_vec(state).map_err(|e| DelegateError::Deser(format!("{e}")))?;
    ctx.set_secret(key, &bytes);
    Ok(())
}

#[cfg(test)]
mod boundary_tests {
    //! Regression tests for the deserialization boundaries.
    //!
    //! `LocalState` and `LocalStateMsg` are reachable from network input via
    //! `DelegateInterface::process`. Every `try_from(&[u8])` must return
    //! `Err(DelegateError::Deser)` rather than panic on malformed input.

    use super::*;

    #[test]
    fn malformed_local_state_bytes_returns_err() {
        let garbage = [0xffu8; 64];
        let result = LocalState::try_from(&garbage[..]);
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn truncated_local_state_json_returns_err() {
        let truncated = br#"{"aliases":{"alice":"#;
        let result = LocalState::try_from(&truncated[..]);
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn malformed_msg_bytes_returns_err() {
        let garbage = [0xffu8; 64];
        let result = LocalStateMsg::try_from(&garbage[..]).map(|_| ());
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    #[test]
    fn empty_msg_bytes_returns_err() {
        let result = LocalStateMsg::try_from(&[][..]).map(|_| ());
        assert!(matches!(result, Err(DelegateError::Deser(_))));
    }

    /// `AliasState` missing the read list (older serialized state) deserializes
    /// with an empty default. Backwards-compat for any state written before the
    /// read-tracking field landed.
    #[test]
    fn alias_state_missing_read_defaults_empty() {
        let json = br#"{"drafts":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.read.is_empty());
    }

    #[test]
    fn alias_state_missing_drafts_defaults_empty() {
        let json = br#"{"read":[1,2]}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.drafts.is_empty());
        assert_eq!(s.read, vec![1, 2]);
    }

    #[test]
    fn round_trip_mixed_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.drafts.insert(
            "00000000-0000-4000-8000-000000000000".into(),
            Draft {
                to: "bob".into(),
                subject: "hi".into(),
                body: "yo".into(),
                updated_at: 42,
            },
        );
        alias.read.push(7);
        alias.kept.insert(
            "7".into(),
            KeptMessage {
                from: "bob".into(),
                title: "hi".into(),
                content: "yo".into(),
                kept_at: 42,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        assert!(back.is_read("alice", 7));
        assert_eq!(back.drafts_of("alice").count(), 1);
        assert_eq!(back.aliases["alice"].kept["7"].content.as_str(), "yo");
    }

    #[test]
    fn alias_state_missing_kept_defaults_empty() {
        let json = br#"{"drafts":{},"read":[1]}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.kept.is_empty());
    }

    /// `AliasState` written before the Sent feature deserialises with an empty
    /// `sent` map. Pre-#47b state must keep loading.
    #[test]
    fn alias_state_missing_sent_defaults_empty() {
        let json = br#"{"drafts":{},"read":[1],"kept":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.sent.is_empty());
    }

    /// `SentMessage` without an explicit `delivery_state` deserialises as
    /// `Pending` (the default).
    #[test]
    fn sent_message_missing_delivery_state_defaults_pending() {
        let json = br#"{"to":"bob","recipient_fingerprint":"abcd","subject":"hi","body":"yo","sent_at":1}"#;
        let s: SentMessage = serde_json::from_slice(json).expect("should deserialise");
        assert_eq!(s.delivery_state, DeliveryState::Pending);
    }

    /// `AliasState` written before the Archive feature deserialises with an
    /// empty `archived` map. Pre-#47c state must keep loading.
    #[test]
    fn alias_state_missing_archived_defaults_empty() {
        let json = br#"{"drafts":{},"read":[],"kept":{},"sent":{}}"#;
        let s: AliasState = serde_json::from_slice(json).expect("should deserialise");
        assert!(s.archived.is_empty());
    }

    #[test]
    fn round_trip_archived_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.archived.insert(
            "9".into(),
            ArchivedMessage {
                from: "bob".into(),
                title: "old".into(),
                content: "stash".into(),
                archived_at: 99,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        assert!(back.is_archived("alice", 9));
        let archived: Vec<_> = back.archived_of("alice").collect();
        assert_eq!(archived.len(), 1);
        assert_eq!(archived[0].1.content.as_str(), "stash");
    }

    #[test]
    fn round_trip_sent_state() {
        let mut state = LocalState::default();
        let alias = state.aliases.entry("alice".into()).or_default();
        alias.sent.insert(
            "00000000-0000-4000-8000-000000000001".into(),
            SentMessage {
                to: "bob".into(),
                recipient_fingerprint: "AB12".into(),
                subject: "hi".into(),
                body: "yo".into(),
                sent_at: 42,
                delivery_state: DeliveryState::Delivered,
            },
        );
        let bytes = serde_json::to_vec(&state).unwrap();
        let back = LocalState::try_from(bytes.as_slice()).unwrap();
        let mut iter = back.sent_of("alice");
        let (_id, sent) = iter.next().expect("one sent");
        assert!(iter.next().is_none());
        assert_eq!(sent.to, "bob");
        assert_eq!(sent.delivery_state, DeliveryState::Delivered);
    }
}
